bitbucket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bitbucketapi.urls')),
    path('api/v1/', include('restapi.urls')),
]

bitbucketapi/urls.py
from django.urls import path
from .views import RegistrationView, RequestsView, NoteView
from .decorators import save_request
from django.contrib.auth.views import LoginView, LogoutView

app_name = "bitbucketapi"
urlpatterns = [
    path("registration", save_request(RegistrationView.as_view()), name="registration"),
    path(
        "login",
        save_request(LoginView.as_view(template_name="bitbucketapi/login.html")),
        name="login",
    ),
    path("logout", save_request(LogoutView.as_view()), name="logout"),
    path("", save_request(RequestsView.as_view()), name="requests"),
    path("note", save_request(NoteView.as_view()), name="note"),
]

restapi/urls.py
from .views import RequestsViewsets, NoteViewsets
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from bitbucketapi.decorators import save_request
from django.contrib.auth import get_user_model

User = get_user_model()

urlpatterns = [
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.jwt")),
    path(
        "notes/creation/",
        save_request(NoteViewsets.as_view({"post": "create"})),
        name="notecreate",
    ),
    path(
        "notes/",
        save_request(
            NoteViewsets.as_view(
                {
                    "get": "list",
                }
            )
        ),
        name="note",
    ),
    path(
        "requests/",
        save_request(
            RequestsViewsets.as_view(
                {
                    "get": "list",
                }
            )
        ),
        name="requests",
    ),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

bitbucketapi/models.py
from django.db import models
from jsonfield import JSONField
from django.contrib.auth import get_user_model

User = get_user_model()


class RequestsList(models.Model):
    ip_user = models.CharField(max_length=100, verbose_name="Ip")
    request_itself = models.CharField(max_length=100, verbose_name="Request")
    json = JSONField(default=None)

    def __str__(self):
        return str(self.ip_user)


class Note(models.Model):
    user_note = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    note = models.CharField(max_length=100, verbose_name="Note")

    def __str__(self):
        return str(self.note)

restapi/models.py
from django.db import models

# Create your models here.

bitbucketapi/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
import re
from django.utils.translation import ugettext as _
from django.contrib.auth import get_user_model

User = get_user_model()


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "password1",
            "password2",
            "first_name",
            "last_name",
        )

    def clean(self):
        cleaned_data = super().clean()

        email_valid = cleaned_data.get("email")
        first_name_valid = cleaned_data.get("first_name")
        last_name_valid = cleaned_data.get("last_name")

        if ("gmail.com" in email_valid) or ("icloud.com" in email_valid):
            msg = _("The email must not contain gmail.com or icloud.com.")
            self.add_error("email", msg)

        if not re.search(
            "^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", email_valid
        ):
            msg = _("Email must not contain prohibited characters.")
            self.add_error("email", msg)

        if not re.search("^[a-zA-Z-]+$", first_name_valid):
            msg = _("First name must contain only letters and dashes.")
            self.add_error("first_name", msg)

        if not re.search("^[a-zA-Z-\s]+$", last_name_valid):
            msg = _("Last name must contain only letters, spaces and dashes.")
            self.add_error("last_name", msg)

bitbucketapi/views.py
from .forms import RegistrationForm
from django.views import generic
from django.urls import reverse_lazy
from .models import RequestsList, Note
from django.contrib.auth.mixins import LoginRequiredMixin


class RegistrationView(generic.CreateView):
    template_name = "bitbucketapi/registration.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("bitbucketapi:registration")


class RequestsView(LoginRequiredMixin, generic.ListView):
    login_url = "bitbucketapi:login"
    template_name = "bitbucketapi/index.html"
    context_object_name = "requestslist"

    def get_queryset(self):
        x_forwarded_for = self.request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            current_ip = x_forwarded_for.split(",")[-1].strip()
        else:
            current_ip = self.request.META.get("REMOTE_ADDR")

        return RequestsList.objects.filter(ip_user=current_ip).order_by("-id")


class NoteView(LoginRequiredMixin, generic.CreateView):
    login_url = "bitbucketapi:login"
    model = Note
    fields = ("note",)
    template_name = "bitbucketapi/note.html"
    success_url = reverse_lazy("bitbucketapi:note")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["note"] = self.model.objects.filter(
            user_note=self.request.user
        ).order_by("-id")
        return context

    def form_valid(self, form):
        form.instance.user_note = self.request.user
        return super().form_valid(form)

restapi/views.py
from rest_framework import viewsets, permissions
from .serializer import RequestsSerializer, NoteSerializer
from bitbucketapi.models import Note, RequestsList
from django.contrib.auth import get_user_model

User = get_user_model()


class NoteViewsets(viewsets.ModelViewSet):
    serializer_class = NoteSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Note.objects.filter(user_note=self.request.user).order_by("-id")


class RequestsViewsets(viewsets.ModelViewSet):
    serializer_class = RequestsSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        x_forwarded_for = self.request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            current_ip = x_forwarded_for.split(",")[-1].strip()
        else:
            current_ip = self.request.META.get("REMOTE_ADDR")

        return RequestsList.objects.filter(ip_user=current_ip).order_by("-id")

bitbucketapi/templates/bitbucketapi/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Requests</title>
</head>
<body>
    <div>
        {% block content %}
            <p><span><a href="{% url 'bitbucketapi:note' %}">Notes</a></span> <span><a href="{% url 'bitbucketapi:logout' %}">Exit</a></span></p>
            {% for r in requestslist %}
                <p>
                    <span>{{ r.ip_user }}</span>
                    <span>{{ r.request_itself }}</span> <br>
                    <span>Data - {{ r.json }}</span>
                </p>
            {% endfor %}
        {% endblock %}
    </div>
</body>
</html>

bitbucketapi/templates/bitbucketapi/login.html
{% extends 'bitbucketapi/index.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <p><a href="{% url 'bitbucketapi:registration' %}">Registration</a></p>
{% endblock %}

bitbucketapi/templates/bitbucketapi/note.html
{% extends 'bitbucketapi/index.html' %}

{% block content %}
    <p><a href="{% url 'bitbucketapi:requests' %}">Requests</a></p>
    <form action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

    <div>
        {% for n in note %}
            <p>{{ n.note }}</p>
        {% endfor %}
    </div>
{% endblock %}

bitbucketapi/templates/bitbucketapi/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
    <p><a href="{% url 'bitbucketapi:login' %}">Sign in</a></p>
</body>
</html>